
RED="#E36464"
BLUE="#56B6C2"
LAVENDER="#B4BEFE"
LIME="#8fce00"

PROMPT='%F{$RED}@%n %F{$BLUE}%3c %F{$LAVENDER}%#%f '
RPROMPT='$(git_prompt_info)'
# RPROMPT='$(git_prompt_info) %F{$LAVENDER}| %F{$LIME}%*'

ZSH_THEME_GIT_PROMPT_PREFIX="%F{yellow}"
ZSH_THEME_GIT_PROMPT_SUFFIX="%f"
ZSH_THEME_GIT_PROMPT_DIRTY=" %F{red}*%f"
ZSH_THEME_GIT_PROMPT_CLEAN=""
