# == Classic ==
# This is a shorthand to override some of the options to be backwards compatible
# with `ls`. It affects the "color"->"when", "sorting"->"dir-grouping", "date"
# and "icons"->"when" options.
classic: false

# == Blocks ==
# Possible values: permission, user, group, context, size, date, name, inode, links, git
blocks:
  - permission
  - user
  # - group
  - size
  - date
  - name

# == Color ==
color:
  when: always
  theme: custom

# == Date ==
date: '+%Y-%m-%d %H:%M:%S'

# == Dereference Symbolic Links ==
dereference: false

# == Icons ==
icons:
  # Possible values: always, auto, never
  when: never
  # Possible values: fancy, unicode
  theme: unicode
  separator: " "

# == Layout ==
# Possible values: grid, tree, oneline
layout: oneline

# == Size ==
# Possible values: default, short, bytes
size: default

# == Sorting ==
sorting:
  # Specify what to sort by.
  # Possible values: extension, name, time, size, version
  column: name
  reverse: false
  # Whether to group directories together and where.
  # When "classic" is set, this is set to "none".
  # Possible values: first, last, none
  dir-grouping: first

# == No Symlink ==
# Whether to omit showing symlink targets
no-symlink: false

# == Total size ==
# Whether to display the total size of directories.
total-size: false

# == Hyperlink ==
# Attach hyperlink to filenames
# Possible values: always, auto, never
hyperlink: never

# == Symlink arrow ==
# Specifies how the symlink arrow display, chars in both ascii and utf8
symlink-arrow: ->

# == Header ==
# Whether to display block headers.
header: false
